#!/usr/bin/awk -f
# TODO: Better filtering, included words, merging fields (e.g. "1|2|3|6" -> "1-3|6")
# formatting the index, command line options, embedded data in script(?), sort
# "words.txt" by frequency and use that instead of "common.txt".
BEGIN {
	while ((getline line<"extra/words.txt") > 0) {
		line = toupper(line);
		dict[line] = line;
	}
	i = 0;
	while ((getline line<"extra/common.txt") > 0) {
		if (i++ > 1000) {
			break;
		}
		line = toupper(line);
		common[line] = line;
	}
}
{
	for (i=1;i<NF;i++) {
		v = toupper($i);
		if (dict[v] == v && length(v) > 3 && common[v] != v) {
			idx[v] = idx[v] "," NR;
		}
	}
}
END {
	for (k in idx) {
		print k, "\t", idx[k];
	}
}
